name = "DeepThought"
description = "A simple blog theme focused on writing powered by Bulma and Zola."
license = "MIT"
homepage = "https://github.com/demiroo/demir"

min_version = "0.1"



[extra]

[author]
name = "Demir"
homepage = "https://demiroo.vercel.app"
